AWSTemplateFormatVersion: 2010-09-09
Description: Create a Word Press installation
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: HVM64
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    t2.large:
      Arch: HVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0135dda7ab64a3faf
    us-east-2:
      HVM64: ami-0135dda7ab64a3faf
    us-east-3:
      HVM64: ami-0135dda7ab64a3faf
Parameters:
  KeyName:
    Description: Name of existing ec2 pair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be name of existing ec2 keypair
  InstanceType:
    Description: WebServer EC2 Instance Type
    Type: String
    Default: "t2.small"
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.nano
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: must be valid EC2 instance type
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: "9"
    MaxLength: "18"
    Default: "0.0.0.0/0"
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be valid IP CIDR range of the form x.x.x.x/x
  DBNAME:
    Default: wordpressdb
    Description: the wordpress database Name
    Type: String
    MaxLength: "64"
    MinLength: "1"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with letter and contain only alphanumeric characters.
  DBUser:
    NoEcho: "true"
    Description: the wordpress database admin account username
    Type: String
    MaxLength: "16"
    MinLength: "8"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must begin with letter and contain only alphanumeric characters.
  DBRootPassword:
    NoEcho: "true"
    Description: the wordpress database admin account password
    Type: String
    MaxLength: "41"
    MinLength: "8"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must begin with letter and contain only alphanumeric characters.
Resources:
  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable Http Access via port 80 and SSH Access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
  WebServer:
    Type: "AWS::EC2::Instance"      
    Properties:
      ImageId: !FindInMap
      - AWSInstanceType2Arch
      - !Ref InstanceType
      - Arch
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      KeyName: !Ref KeyName
    Metadata:
      Instance:
        Description: "This server hosts on murthy cloud"
  IPAddress:
    Type: "AWS::EC2::EIP"
  IPAssoc:
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      InstanceId: !Ref WebServer
      EIP: !Ref IPAddress
Outputs:
  WebsiteURL:
    Value: !Join
      - ""
      - - "http://"
        - !GetAtt
          - WebServer
          - PublicDnsName
        - /wordpress
    Description: Wordpress Website
